
'use client'
import { useState } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AIPrompt from "./components/Prompt";
import { Providers } from "./providers";
import { Flex, Button, Link, Heading, Box, } from '@chakra-ui/react';
import { SearchIcon } from '@chakra-ui/icons';
import SearchModal from './components/SearchModal';
import { AppWrapper } from '@/context';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en" >
      <body className={inter.className}  >
        <AppWrapper>
          <Providers>
            {children}
          </Providers>
        </AppWrapper>
      </body>
    </html >
  );
}

export default RootLayout;
